### ISSUE TITLE
AMD Ryzen Support for reading CPU voltage and Temperature 

### ISSUE THREAD

**Issue by Scaredycrow** [openhardwaremonitor/openhardwaremonitor#957] opened 2017-03-24 01:03 UTC
Currently can read only load and core load metrics from Ryzen CPU's. 

Clocks, Voltage, Temperature and Fan speeds all appear to be missing (possibly also a need to support the new chipsets (X370, B350 etc)

**Comment by bbaydar** [comment] 2017-03-24 01:07
Seconding this request.

**Comment by liabilityman** [comment] 2017-03-25 17:18
Thirding

**Comment by ooheyC** [comment] 2017-03-28 07:17
Fourthing

**Comment by Extarys** [comment] 2017-03-28 08:52
It would be cool since no other linux hardware monitoring tool are still in dev sadly. +1

**Comment by DarthDestroyer** [comment] 2017-03-28 10:39
#961

No one, without a Ryzen,  could help you when nobody posts a report! 

The best known Answer to anything should be:
No help possible without a report :-/

Also, please see that you miss two (or more) parts! 
not only the cpu may be not supported, yet. 
the Mainboard is missing, too! 

Kind Regards

**Comment by Soyasi** [comment] 2017-03-28 14:12
hello!! look at this link https://github.com/groeck/it87/issues/10

**Comment by cybercatgurrl** [comment] 2017-03-29 02:03
Here's a hardware report. [OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/877564/OpenHardwareMonitor.Report.txt)

**Comment by ThePunisher69** [comment] 2017-03-29 02:10
Is there an echo in here?

https://github.com/openhardwaremonitor/openhardwaremonitor/issues/950

**Comment by ooheyC** [comment] 2017-03-29 08:58
The vendorID is 0x1463. But DeviceIoCntrol return error is 31. why?

**Comment by DarthDestroyer** [comment] 2017-03-29 10:20
@ooheyC, if you are familar with coding... there is a pull request to enumerate more informations for unknown cpus... maybe this could help? 

atleast, what i had seen from the less reports:
there seems to be an error at Estimated Time Stamp Counter Frequency Error: 0.51196 Mhz (source @cybercatgurrl)

**Comment by liabilityman** [comment] 2017-04-08 00:52
Here's another hardware report (Ryzen R7 1700). [OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/907129/OpenHardwareMonitor.Report.txt)

**Comment by liabilityman** [comment] 2017-04-08 02:59
@DarthDestroyer I'm not at all proficient with C#, but I think I managed to compile a version with @rmattuschka 's edits and run a report on my Ryzen system. Hope this helps! [OpenHardwareMonitor.Report.rmattuschka.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/907181/OpenHardwareMonitor.Report.rmattuschka.txt)

**Comment by DarthDestroyer** [comment] 2017-04-08 12:58
#836 is that, what i mean. 
i cant find, what there is added in your report...

**Comment by liabilityman** [comment] 2017-04-11 20:02
@DarthDestroyer Yeah I also tried #836 but I'm not sure what it's supposed to add either. 

Is there a debug version or debug mode I can run that would give you more information?

**Comment by DarthDestroyer** [comment] 2017-04-11 20:11
All Data that could be used for debugging is found in the report! you get all collected informations there, also errors or problems! 

that addition should show up in it! ;-)

**Comment by Kraust** [comment] 2017-04-21 02:42
@DarthDestroyer I Just submitted a report for my 1700. I would absolutely l-o-v-e Ryzen support so I can properly monitor temps and not need to rely on Ryzen Master.

**Comment by DarthDestroyer** [comment] 2017-04-21 15:38
that wasnt a failure, but i have to say that i cant access those ;-)
could you also upload your report to this issue?

**Comment by Kraust** [comment] 2017-04-21 17:35
[OpenHardwareMonitor-Kraust.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/947842/OpenHardwareMonitor-Kraust.Report.txt)

My bad, Have a report

**Comment by Kraust** [comment] 2017-04-23 12:47
In the mean time I am working on implementing support for the AX370 Gaming K7:
http://i.imgur.com/qEFUFPW.png

**Comment by laffer1** [comment] 2017-05-12 19:34
Here's another report for a Ryzen 1700 with the Asus Prime X370-pro
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/997766/OpenHardwareMonitor.Report.txt)

**Comment by Extarys** [comment] 2017-05-17 09:05
Is it possible to install this and generate a report under Linux?

**Comment by NoXPhasma** [comment] 2017-06-11 11:24
Under Linux it doesn't show anything beside the Processor and Motherboard name.

Board: ASUS Prime x370-Pro
CPU: AMD Ryzen 7 1700

[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1066370/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment] 2017-06-11 11:28
It will not show more in linux! 

If you search "Linux" , it is well commented why and on what it depends :-(

**Comment by NoXPhasma** [comment] 2017-06-11 11:39
I don't understand, where should I search for Linux to find those dependencies? And just for the record, I can view lots of data with LMSensors (Voltages, Temperatures, Fan Speeds), I don't see why this shouldn't be possible with this software.

**Comment by DarthDestroyer** [comment] 2017-06-11 11:43
Go back to Issues (List), type into the Searchbox: "Linux" and you will get the posts about it! 

I didnt say, that it is impossible... Afaik, there is no one working on Linux Support, atm!

**Comment by Kraust** [comment] 2017-06-11 13:37
OT: I was looking into this issue again this weekend, and I still haven't found the PCI Device/Register where temperatures are located. It has most certainly changed and AMD hasn't released their BKDG for Family 17h yet. 

I did manage to get Bus Speed, as that register was available in a guide that they released last month.

On the Linux side I don't know of anyone who has implemented this either. If I could find out the PCI Device/Register where this data is held I could probably implement this fairly easily (Probably not on Linux tho, as I don't regularly use it).

**Comment by DarthDestroyer** [comment] 2017-06-11 13:47
For Linux,  this Issue was one of the Search-Results i had meant: #867

The MSR Addition from hirschmann looks not so bad, but i dont have a Linux with GUI available right now :-(

**Comment by BennehBoy** [comment] 2017-07-13 10:18
I found a fork of kraust's work with a branch that covers the ITE IT8665 - this gives another piece of the puzzle but is still WIP -> https://github.com/azuisleet/openhardwaremonitor/tree/IT8665E

This gives voltages, temps, and fans.  CPU temp I think needs some conditional code adding somewhere based on cpu type because it appears to include the offset (or part of!) - not sure it's possible to bake this into the superio area however and we may need to wait for the BKDG in order to update the AMD10 code.

**Comment by JernejL** [comment] 2017-08-18 11:27
Check https://linuxconfig.org/monitor-amd-ryzen-temperatures-in-linux-with-latest-kernel-modules - that apparently works.

**Comment by Terrails** [comment] 2017-08-31 14:53
Another report with Ryzen 5 1600 and B350 motherboard
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1267492/OpenHardwareMonitor.Report.txt)

**Comment by Robyer** [comment] 2017-09-05 07:40
Now it seems they finished it in https://github.com/groeck/lm-sensors/issues/16 (as @Soyasi posted this link before).

**Comment by KyodaiKen** [comment] 2017-09-30 13:57
Hey! I would like to send a report file for the Ryzen Threadripper 1950X on an ASUS ROG Zenith Extreme x399 chipset motherboard, but OpenHardwareMonitor then hangs and I can't even kill it, nor can I reboot. CPU-Usage is absolutely ZERO. I cannot help at all and would like to see all information available on my setup....

**Comment by KyodaiKen** [comment] 2017-09-30 14:08
Hello again. Here is a CPUz report instead attached.
[FELINE.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1346448/FELINE.txt)

**Comment by Vahalu** [comment] 2017-10-27 07:00
Mobo: X370 GAMING PRO CARBON
CPU: R5 1600x
Report: [OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1421045/OpenHardwareMonitor.Report.txt)

**Comment by jumar** [comment] 2017-11-13 14:53
isn't this issue closed by https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/17 ?

**Comment by Kraust** [comment] 2017-11-13 15:06
A pull request was never made to notify people that these changes were made. It seems like the person who made the fork doesn't intend to merge his changes back into this project (regardless of whether or not this repo is actually active or not).

**Comment by Trip2009** [comment] 2017-12-07 13:25
Another one for ASUS Prime B350-Plus
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1539217/OpenHardwareMonitor.Report.txt)

**Comment by jctmf** [comment] 2017-12-13 03:56
Another one for DELL INSPIRON 5675. X370 chipset
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1554079/OpenHardwareMonitor.Report.txt)

**Comment by FireFrenzy** [comment] 2017-12-16 15:06
HWInfo can read core temps, so its atelast POSSIBLE todo it and on my 1950x it seems to have the same 27 degree ofset everyone was freaking out about during the r7 launch... 

If i need to provide something more complex then screenshots for win10 64 Pro, let me know what to do and i'll hook you up...

**Comment by dasMenz** [comment] 2018-03-27 19:09
One more for ASUS CROSSHAIR VI HERO
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1853423/OpenHardwareMonitor.Report.txt)

**Comment by FoxyRawrs** [comment] 2018-04-29 00:31
Asus ROG Strix x370-f gaming 
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/1958320/OpenHardwareMonitor.Report.txt)

**Comment by Kallestofeles** [comment] 2018-07-14 14:48
Mobo: ASUS Strix x470-f
CPU: Ryzen gen2 2700X
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/2195017/OpenHardwareMonitor.Report.txt)
Let's make the best monitoring tool even better. :)

**Comment by DarthDestroyer** [comment] 2018-07-14 15:03
@Kallestofeles

Chip ID: Unknown ITE with ID 0x8665 at 0x2E/0x2F

And you are using a outdated Version ;-)

**Comment by Kallestofeles** [comment] 2018-07-14 15:23
@DarthDestroyer 
The version I'm using is 0.8.0 beta which is the latest on the website: https://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0-beta.zip
If that's not the latest, then someone should update the webpage. :)
But I can confirm that all the data is there when using librehardwaremonitor branch build.

**Comment by Kraust** [comment] 2018-07-14 15:28
OHM is no longer supported and none of us have access to actually pushing new code changes. I would suggest you use HWiNFO as its really the only modern reliable hardware monitor out there.

**Comment by DarthDestroyer** [comment] 2018-07-14 15:34
http://openhardwaremonitor.org/files/openhardwaremonitor-v0.8.0.3-alpha.zip

It isnt that bad and far from a Problem to get further with OHM! 
Fork it, Join the PRs and you have what you want! 

For only "using" there are enough options! But for me, it is the part of implementing into other tools why i try to help where i can! 
The Libre Guys are one Option, too!

**Comment by mittyredstar** [comment] 2020-01-31 12:41
ryzen 7 3700x with asus x470 prime pro no temps :((
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4139401/OpenHardwareMonitor.Report.txt)

**Comment by alexandru2882** [comment] 2020-03-23 15:24
Ryzen 7 2700X + MSI B450 TOMAHAWK
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4370286/OpenHardwareMonitor.Report.txt)

**Comment by moellerm** [comment] 2020-05-12 21:58
This should be fixed in OHM version 0.9.0 and later.

**Closed by moellerm** 2020-05-12 21:58 UTC
