### ISSUE TITLE
Freeze When Display DPI/Resolution changed

### ISSUE THREAD

**Issue by Pein1911** [openhardwaremonitor/openhardwaremonitor#1252] opened 2020-04-18 14:37 UTC
My display is 1440p, sometime if i load a game at 1080p fullscreen, then I quit game and  OHM tray icon will be freeze

**Comment by wingo1** [comment] 2020-05-02 11:15
Same problem !

**Comment by pkypkygit** [comment] 2020-05-14 06:32
The same problem here. 

The easiest way to reproduce:
1. set windows DPI scaling to 100%
2. start OpenHWMonitor, minimize it 
3. set windows DPI scaling to 125%
4. OpenHWMonitor is frozen, stops redrawing values in systray

**Comment by moellerm** [comment] 2020-05-24 22:19
This should be fixed in version 0.9.3.

**Closed by moellerm** 2020-05-24 22:19 UTC

**Comment by pkypkygit** [comment] 2020-05-25 06:20
Hello.

I have tried it in version 0.9.3 and the problem is still there. Windows TaskManager says that Open Hardware Monitor is "not responding".

Regards.

**Comment by pkypkygit** [comment] 2020-05-25 06:24
Thanks!

Confirmed - I have tried the new version and it works.

Regards.

> 
> 
> This should be fixed in version 0.9.4.
