### ISSUE TITLE
Bug CPU

### ISSUE THREAD

**Issue by Brice3666** [openhardwaremonitor/openhardwaremonitor#1269] opened 2020-05-02 01:58 UTC
![image](https://user-images.githubusercontent.com/64672052/80852467-1dd0ea80-8c29-11ea-9456-79551fca2c51.png)
[OpenHardwareMonitor.Report.txt](https://github.com/openhardwaremonitor/openhardwaremonitor/files/4566905/OpenHardwareMonitor.Report.txt)

**Comment by DarthDestroyer** [comment] 2020-05-02 06:57
Ring0

Status: Installing driver "C:\Users\PCBrice\Desktop\OpenHardwareMonitor\OpenHardwareMonitorLib.sys" failed and file exists
First Exception: Service already exists
Second Exception: StartService returned the error: Le pilote nâ€™a pas pu Ãªtre chargÃ©, car son appel de lâ€™initialisation a Ã©chouÃ©. (Exception de HRESULT : 0x80070287)

**Comment by Brice3666** [comment] 2020-05-02 11:58
how i made it work

**Comment by DarthDestroyer** [comment] 2020-05-02 13:01
Check if anything is blocking the Service!
Anti Virus? Any kind of Anticheat...

**Comment by Fhosho** [comment] 2020-05-05 17:52
I have the exact same problem! It works when i System restore my computer just one day back, but when i go to sleep and wake up the next morning the issue is right there again! Solutions ?

**Comment by moellerm** [comment] 2020-05-05 20:35
Thx for the feedback. This seems to be a duplicate of #1268

**Closed by moellerm** 2020-05-05 20:35 UTC
