### ISSUE TITLE
Log file location

### ISSUE THREAD

**Issue by GoogleCodeExporter** [openhardwaremonitor/openhardwaremonitor#718] opened 2015-08-23 21:38 UTC
```
It would be useful if the location of the log file could be chosen instead of 
being in the program folder by default.  I wish to store the log files in a 
network folder but the program cannot be run from a network folder because the 
WinRing0_1_2_0 service fails to start.

```

Original issue reported on code.google.com by `co...@ferrington.co.uk` on 17 Jul 2015 at 6:05

**Comment by moellerm** [comment] 2015-12-20 15:05
This is a duplicate of issue #644.

**Closed by moellerm** 2015-12-20 15:05 UTC
Labels: enhancement
